Repository pikvm/ustreamer, pull requests merged in 2023-10, with the labels that each got.

#226 SSL Proxy Scripts
  tools/ssl/README.md
  tools/ssl/ssl-config.sh
  tools/ssl/ustreamer-proxy
Labels: type:feature, resolution:fixed

#233 Multi Planar device support
  src/libs/frame.c
  src/ustreamer/device.c
  src/ustreamer/device.h
  src/ustreamer/encoders/cpu/encoder.c
Labels: type:feature, resolution:fixed

#236 Correct typo on 'interval'
  man/ustreamer.1
  src/ustreamer/options.c
Labels: type:bug, resolution:fixed

#235 Optimize JPEG scanline copy of yuv format
  src/ustreamer/encoders/cpu/encoder.c
Labels: type:feature
